package org.openbased.event;

public enum EventType {
    MEDIA_ADDED,
    MEDIA_UPDATED,
    MEDIA_REMOVED,

    LIBRARY_SCAN_STARTED,
    LIBRARY_SCAN_COMPLETED,

    PLAYBACK_STARTED,
    PLAYBACK_STOPPED,
    PLAYBACK_PROGRESS,

    UPLOAD_STARTED,
    UPLOAD_COMPLETED,
    UPLOAD_FAILED,

    USER_CREATED,
    USER_UPDATED
}
